package header_test

import (
	"os"

	"github.com/yourusername/vaultpull/internal/header"
)

func ExampleWriter_Write() {
	opts := header.Options{
		Source:  "secret/myapp",
		Warning: true,
		// Timestamp omitted for deterministic output
	}
	w := header.New(opts)
	w.Write(os.Stdout)
	// Output:
	// # This file is generated by vaultpull. Do not edit manually.
	// # Source: secret/myapp
}
