// Package header injects metadata comments at the top of generated .env files.
package header

import (
	"fmt"
	"io"
	"strings"
	"time"
)

// Options controls what metadata is included in the header.
type Options struct {
	Source    string
	Timestamp bool
	Warning   bool
}

// DefaultOptions returns sensible defaults.
func DefaultOptions() Options {
	return Options{
		Timestamp: true,
		Warning:   true,
	}
}

// Writer writes a metadata header to an io.Writer.
type Writer struct {
	opts Options
	now  func() time.Time
}

// New creates a new header Writer.
func New(opts Options) *Writer {
	return &Writer{opts: opts, now: time.Now}
}

// Write emits the header lines to w.
func (h *Writer) Write(w io.Writer) error {
	lines := []string{}

	if h.opts.Warning {
		lines = append(lines, "# This file is generated by vaultpull. Do not edit manually.")
	}
	if h.opts.Source != "" {
		lines = append(lines, fmt.Sprintf("# Source: %s", h.opts.Source))
	}
	if h.opts.Timestamp {
		lines = append(lines, fmt.Sprintf("# Generated: %s", h.now().UTC().Format(time.RFC3339)))
	}

	if len(lines) == 0 {
		return nil
	}

	_, err := fmt.Fprintln(w, strings.Join(lines, "\n"))
	return err
}

// Lines returns the header as a slice of comment strings.
func (h *Writer) Lines() []string {
	var out []string
	if h.opts.Warning {
		out = append(out, "# This file is generated by vaultpull. Do not edit manually.")
	}
	if h.opts.Source != "" {
		out = append(out, fmt.Sprintf("# Source: %s", h.opts.Source))
	}
	if h.opts.Timestamp {
		out = append(out, fmt.Sprintf("# Generated: %s", h.now().UTC().Format(time.RFC3339)))
	}
	return out
}
